name: Deploy Portofolio
on: [push, mirror_update, workflow_dispatch]

jobs:
  deploy-noosa:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and Deploy
        run: |
          # Perintah ini bakal jalan di server Noosa kamu
          docker compose down
          docker compose up -d --build

      - name: Send Notification
        uses: appleboy/telegram-action@master
        if: always()
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            🚀 *Deployment Portofolio v2*
            Status: ${{ job.status == 'success' && '✅ SUCCESS' || '❌ FAILED' }}
            URL: rikonusa.cloud